version: 1
project: Automatismos VMC
sources:
  - id: doc_NEUTRO
    title: "Manual_Encadenamiento_IA_NEUTRO"
    date: "2025-09-06"
    authors: ["@usuario"]
    path: "data/raw_chats/Manual_Encadenamiento_IA_NEUTRO.md"
pii_policy: config/pii_patterns.yaml
out:
  drafts_json: "data/intermediate/prompts_draft.json"
  canon_json: "prompts/canonical/prompts_canon.json"
  evidence_dir: "data/evidences"

# EXPORT_SEAL v1
# project: Automatismos VMC
# prompt_id: HARVEST_MANIFEST
# version: v1
# file: config/harvest_manifest.yaml
# lang: yaml
# created_at: 2025-09-16T00:00:00Z
# author: @matias.portugau
# origin: Librería agnóstica — manifest de chats
# body_sha256: TBD
