name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install Node deps
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci || npm install

      - name: Lint
        run: make lint

      - name: Tests
        run: make test

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: corepack enable
      - run: corepack prepare pnpm@9.12.0 --activate
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm lint
      - run: pnpm typecheck
