name: Mejora Continua de Prompts (Branch)
on:
  push:
    branches:
      - '**'
    paths:
      - 'MasterPrompts/**'
      - 'scripts/**'
      - '.github/workflows/prompts-branch.yml'
jobs:
  mejorar-prompts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Analizar y mejorar prompts (carpeta MasterPrompts)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 scripts/prompt_library_watcher_v2_1.py \
            --paths ./MasterPrompts \
            --mode API \
            --orchestrator scripts/PE-QA_Orchestrator_v1_3.prompt.md \
            --root-master ./MasterPrompts \
            --organize move
      - name: Commit de los prompts mejorados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(prompts): Mejora automática de prompts por CI/CD'
          branch: ${{ github.ref_name }}
