name: Mejora Continua de Prompts (Autopilot 24/7)

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: {}

concurrency:
  group: prompts-autopilot
  cancel-in-progress: false

jobs:
  autopilot-evolve:
    runs-on: ubuntu-latest
    env:
      LLM_PROVIDER: LOCAL
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run evolver (LOCAL)
        env:
          PROMPT_WATCHER_MAX_FILES: '60'
        run: |
          python3 scripts/prompt_library_watcher_v2_1.py \
            --paths ./MasterPrompts/PromptLibrary_Organized/original \
            --mode LOCAL \
            --root-master ./MasterPrompts/PromptLibrary_Organized

      - name: Pairwise judge + Elo
        if: env.LLM_PROVIDER != 'LOCAL' && env.OPENAI_API_KEY != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          JUDGE_MAX_PAIRS: '30'
        run: |
          python3 scripts/judge_pairwise_elo.py ./MasterPrompts

      - name: Generate simple run summary
        run: |
          python3 scripts/generate_run_report.py ./MasterPrompts

      - name: Generate detailed reports (mods, Elo, library win-rate)
        run: |
          python3 scripts/generate_detailed_report.py ./MasterPrompts

      - name: CI gates (block regressions & safety)
        if: env.LLM_PROVIDER != 'LOCAL'
        env:
          CI_MIN_EVOLVED_WIN_RATE: '0.55'
          CI_MIN_DECISIONS: '10'
          CI_MAX_MANUAL_RATIO: '0.10'
          CI_BLOCK_ON_SAFETY: 'false'
        run: |
          python3 scripts/ci_gates.py ./MasterPrompts

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(nightly): Autopilot prompt evolution artifacts'
          branch: ${{ github.ref_name }}
